// <auto-generated />
using System;
using Assignment3.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment3.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208000103_AnimalsTables")]
    partial class AnimalsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment3.Api.Models.AnimalTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Affection")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HpMax")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.ToTable("AnimalTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Affection = 3,
                            Attack = 5,
                            Defense = 4,
                            HpMax = 30,
                            Kind = "dog",
                            Level = 1
                        },
                        new
                        {
                            Id = 2,
                            Affection = 4,
                            Attack = 6,
                            Defense = 3,
                            HpMax = 28,
                            Kind = "cat",
                            Level = 1
                        },
                        new
                        {
                            Id = 3,
                            Affection = 2,
                            Attack = 4,
                            Defense = 5,
                            HpMax = 32,
                            Kind = "hamster",
                            Level = 1
                        },
                        new
                        {
                            Id = 4,
                            Affection = 2,
                            Attack = 8,
                            Defense = 5,
                            HpMax = 34,
                            Kind = "fox",
                            Level = 1
                        },
                        new
                        {
                            Id = 5,
                            Affection = 2,
                            Attack = 7,
                            Defense = 6,
                            HpMax = 36,
                            Kind = "owl",
                            Level = 1
                        },
                        new
                        {
                            Id = 6,
                            Affection = 1,
                            Attack = 6,
                            Defense = 8,
                            HpMax = 40,
                            Kind = "boar",
                            Level = 1
                        });
                });

            modelBuilder.Entity("Assignment3.Api.Models.PlayerAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Affection")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HpCurrent")
                        .HasColumnType("int");

                    b.Property<int>("HpMax")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("PlayerAnimals");
                });

            modelBuilder.Entity("Assignment3.Api.Models.PlayerAnimal", b =>
                {
                    b.HasOne("Assignment3.Api.Models.AnimalTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
